server:
  port: 8086
  servlet:
    context-path: /api/hello-blog-service
spring:
  profiles:
    active: dev
  datasource:
    name: helloblog
    url:  ${MYSQL_DATABASE:jdbc:mysql://localhost:3306/helloblog?useSSL=false&characterEncoding=utf8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: helloblog
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.byteblogs.helloblog.*.dao
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: false
      #删除
      logic-delete-value: 1
      #不删除
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
